repeat = 10

[[experiment]]
output = "ablation.ndjson"
numa = [{ policy = "bind", node = 0 }]
thread_count = [1, 2, 4, 8, 16, 32]
process_count = [1]
allocator = [{ name = "cxlalloc" }]

[experiment.allocator_config]
numa = [{ policy = "bind", node = 1 }]
size = [4294967296]

[[experiment.benchmark]]
kind = "thread_test"
iteration_count = [840]
operation_count = [10000]
object_size = [8]

[[experiment.benchmark]]
kind = "xmalloc"
operation_count = [8400]
